//// <auto-generated />
//// author:vipwan@outlook.com 万雅虎
//// issue:https://github.com/vipwan/Biwen.AutoClassGen/issues
//// 如果你在使用中遇到问题,请第一时间issue,谢谢!
//// This file is generated by Biwen.AutoClassGen.AutoDtoSourceGenerator
//using System;
//using System.Collections.Generic;
//using System.ComponentModel;
//using System.ComponentModel.DataAnnotations;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;

//#pragma warning disable
////generate User-UserDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Entitys;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class UserDto
//    {
//        /// <inheritdoc cref = "User.FirstName"/>
//        public string FirstName { get; set; }
//        /// <inheritdoc cref = "User.LastName"/>
//        public string LastName { get; set; }
//        /// <inheritdoc cref = "User.Age"/>
//        public int? Age { get; set; }
//        /// <inheritdoc cref = "User.FullName"/>
//        public string? FullName { get; set; }
//        /// <inheritdoc cref = "Info.Email"/>
//        public string? Email { get; set; }
//        /// <inheritdoc cref = "Other.Remark"/>
//        public string? Remark { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Entitys
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class UserToUserDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User from, UserDto to);
//        /// <summary>
//        /// mapper to UserDto
//        /// </summary>
//        /// <returns></returns>
//        public static UserDto MapperToUserDto(this User model)
//        {
//            if (model == null)
//                return null;
//            var retn = new UserDto()
//            {
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                FullName = model.FullName,
//                Email = model.Email,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo UserDto
//        /// </summary>
//        public static IQueryable<UserDto> ProjectToUserDto(this IQueryable<User> query)
//        {
//            return query.Select(model => model.MapperToUserDto());
//        }
//    }

//    public static partial class UserDtoToUserExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(UserDto from, User to);
//        /// <summary>
//        /// mapper to User
//        /// </summary>
//        /// <returns></returns>
//        public static User MapperToUser(this UserDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User()
//            {
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                Email = model.Email,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate User-User2Dto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Entitys;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class User2Dto
//    {
//        /// <inheritdoc cref = "User.Id"/>
//        public string Id { get; set; }
//        /// <inheritdoc cref = "User.FirstName"/>
//        public string FirstName { get; set; }
//        /// <inheritdoc cref = "User.LastName"/>
//        public string LastName { get; set; }
//        /// <inheritdoc cref = "User.Age"/>
//        public int? Age { get; set; }
//        /// <inheritdoc cref = "User.FullName"/>
//        public string? FullName { get; set; }
//        /// <inheritdoc cref = "Other.Remark"/>
//        public string? Remark { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Entitys
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class UserToUser2DtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User from, User2Dto to);
//        /// <summary>
//        /// mapper to User2Dto
//        /// </summary>
//        /// <returns></returns>
//        public static User2Dto MapperToUser2Dto(this User model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User2Dto()
//            {
//                Id = model.Id,
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                FullName = model.FullName,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo User2Dto
//        /// </summary>
//        public static IQueryable<User2Dto> ProjectToUser2Dto(this IQueryable<User> query)
//        {
//            return query.Select(model => model.MapperToUser2Dto());
//        }
//    }

//    public static partial class User2DtoToUserExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User2Dto from, User to);
//        /// <summary>
//        /// mapper to User
//        /// </summary>
//        /// <returns></returns>
//        public static User MapperToUser(this User2Dto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User()
//            {
//                Id = model.Id,
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate User-User3Dto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Entitys;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class User3Dto
//    {
//        /// <inheritdoc cref = "User.Id"/>
//        public string Id { get; set; }
//        /// <inheritdoc cref = "User.FirstName"/>
//        public string FirstName { get; set; }
//        /// <inheritdoc cref = "User.LastName"/>
//        public string LastName { get; set; }
//        /// <inheritdoc cref = "User.Age"/>
//        public int? Age { get; set; }
//        /// <inheritdoc cref = "User.FullName"/>
//        public string? FullName { get; set; }
//        /// <inheritdoc cref = "Other.Remark"/>
//        public string? Remark { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Entitys
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class UserToUser3DtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User from, User3Dto to);
//        /// <summary>
//        /// mapper to User3Dto
//        /// </summary>
//        /// <returns></returns>
//        public static User3Dto MapperToUser3Dto(this User model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User3Dto()
//            {
//                Id = model.Id,
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                FullName = model.FullName,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo User3Dto
//        /// </summary>
//        public static IQueryable<User3Dto> ProjectToUser3Dto(this IQueryable<User> query)
//        {
//            return query.Select(model => model.MapperToUser3Dto());
//        }
//    }

//    public static partial class User3DtoToUserExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User3Dto from, User to);
//        /// <summary>
//        /// mapper to User
//        /// </summary>
//        /// <returns></returns>
//        public static User MapperToUser(this User3Dto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User()
//            {
//                Id = model.Id,
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate User-User4Dto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Entitys;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial record class User4Dto
//    {
//        /// <inheritdoc cref = "User.Id"/>
//        public string Id { get; set; }
//        /// <inheritdoc cref = "User.FirstName"/>
//        public string FirstName { get; set; }
//        /// <inheritdoc cref = "User.LastName"/>
//        public string LastName { get; set; }
//        /// <inheritdoc cref = "User.Age"/>
//        public int? Age { get; set; }
//        /// <inheritdoc cref = "User.FullName"/>
//        public string? FullName { get; set; }
//        /// <inheritdoc cref = "Other.Remark"/>
//        public string? Remark { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Entitys
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class UserToUser4DtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User from, User4Dto to);
//        /// <summary>
//        /// mapper to User4Dto
//        /// </summary>
//        /// <returns></returns>
//        public static User4Dto MapperToUser4Dto(this User model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User4Dto()
//            {
//                Id = model.Id,
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                FullName = model.FullName,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo User4Dto
//        /// </summary>
//        public static IQueryable<User4Dto> ProjectToUser4Dto(this IQueryable<User> query)
//        {
//            return query.Select(model => model.MapperToUser4Dto());
//        }
//    }

//    public static partial class User4DtoToUserExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User4Dto from, User to);
//        /// <summary>
//        /// mapper to User
//        /// </summary>
//        /// <returns></returns>
//        public static User MapperToUser(this User4Dto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User()
//            {
//                Id = model.Id,
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate TestServiceDto-TestService3
//namespace Biwen.AutoClassGen.TestConsole.Services
//{
//    using Biwen.AutoClassGen.TestConsole.Services;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class TestService3
//    {
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Services
//{
//    using Biwen.AutoClassGen.TestConsole.Services;
//    using System.Linq;

//    public static partial class TestServiceDtoToTestService3Extentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(TestServiceDto from, TestService3 to);
//        /// <summary>
//        /// mapper to TestService3
//        /// </summary>
//        /// <returns></returns>
//        public static TestService3 MapperToTestService3(this TestServiceDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new TestService3()
//            {
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo TestService3
//        /// </summary>
//        public static IQueryable<TestService3> ProjectToTestService3(this IQueryable<TestServiceDto> query)
//        {
//            return query.Select(model => model.MapperToTestService3());
//        }
//    }

//    public static partial class TestService3ToTestServiceDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(TestService3 from, TestServiceDto to);
//        /// <summary>
//        /// mapper to TestServiceDto
//        /// </summary>
//        /// <returns></returns>
//        public static TestServiceDto MapperToTestServiceDto(this TestService3 model)
//        {
//            if (model == null)
//                return null;
//            var retn = new TestServiceDto()
//            {
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate User-User5Dto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Entitys;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial record class User5Dto
//    {
//        /// <inheritdoc cref = "User.FirstName"/>
//        public string FirstName { get; set; }
//        /// <inheritdoc cref = "User.LastName"/>
//        public string LastName { get; set; }
//        /// <inheritdoc cref = "User.Age"/>
//        public int? Age { get; set; }
//        /// <inheritdoc cref = "User.FullName"/>
//        public string? FullName { get; set; }
//        /// <inheritdoc cref = "Info.Email"/>
//        public string? Email { get; set; }
//        /// <inheritdoc cref = "Other.Remark"/>
//        public string? Remark { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Entitys
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class UserToUser5DtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User from, User5Dto to);
//        /// <summary>
//        /// mapper to User5Dto
//        /// </summary>
//        /// <returns></returns>
//        public static User5Dto MapperToUser5Dto(this User model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User5Dto()
//            {
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                FullName = model.FullName,
//                Email = model.Email,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo User5Dto
//        /// </summary>
//        public static IQueryable<User5Dto> ProjectToUser5Dto(this IQueryable<User> query)
//        {
//            return query.Select(model => model.MapperToUser5Dto());
//        }
//    }

//    public static partial class User5DtoToUserExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(User5Dto from, User to);
//        /// <summary>
//        /// mapper to User
//        /// </summary>
//        /// <returns></returns>
//        public static User MapperToUser(this User5Dto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new User()
//            {
//                FirstName = model.FirstName,
//                LastName = model.LastName,
//                Age = model.Age,
//                Email = model.Email,
//                Remark = model.Remark,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate VenueImage-VenueImageDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Entitys;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class VenueImageDto
//    {
//        /// <inheritdoc cref = "VenueImage.VenueId"/>
//        public string? VenueId { get; set; }
//        /// <inheritdoc cref = "VenueImage.Url"/>
//        public string? Url { get; set; }
//        /// <inheritdoc cref = "VenueImage.OrderId"/>
//        public long? OrderId { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Entitys
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class VenueImageToVenueImageDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(VenueImage from, VenueImageDto to);
//        /// <summary>
//        /// mapper to VenueImageDto
//        /// </summary>
//        /// <returns></returns>
//        public static VenueImageDto MapperToVenueImageDto(this VenueImage model)
//        {
//            if (model == null)
//                return null;
//            var retn = new VenueImageDto()
//            {
//                VenueId = model.VenueId,
//                Url = model.Url,
//                OrderId = model.OrderId,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo VenueImageDto
//        /// </summary>
//        public static IQueryable<VenueImageDto> ProjectToVenueImageDto(this IQueryable<VenueImage> query)
//        {
//            return query.Select(model => model.MapperToVenueImageDto());
//        }
//    }

//    public static partial class VenueImageDtoToVenueImageExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(VenueImageDto from, VenueImage to);
//        /// <summary>
//        /// mapper to VenueImage
//        /// </summary>
//        /// <returns></returns>
//        public static VenueImage MapperToVenueImage(this VenueImageDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new VenueImage()
//            {
//                VenueId = model.VenueId,
//                Url = model.Url,
//                OrderId = model.OrderId,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate Venue-VenueDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Entitys;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class VenueDto
//    {
//        /// <inheritdoc cref = "Venue.BusinessId"/>
//        public string? BusinessId { get; set; }
//        /// <inheritdoc cref = "Venue.Name"/>
//        public string? Name { get; set; }
//        /// <inheritdoc cref = "Venue.Address"/>
//        public string? Address { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Entitys
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class VenueToVenueDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(Venue from, VenueDto to);
//        /// <summary>
//        /// mapper to VenueDto
//        /// </summary>
//        /// <returns></returns>
//        public static VenueDto MapperToVenueDto(this Venue model)
//        {
//            if (model == null)
//                return null;
//            var retn = new VenueDto()
//            {
//                Name = model.Name,
//                Address = model.Address,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo VenueDto
//        /// </summary>
//        public static IQueryable<VenueDto> ProjectToVenueDto(this IQueryable<Venue> query)
//        {
//            return query.Select(model => model.MapperToVenueDto());
//        }
//    }

//    public static partial class VenueDtoToVenueExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(VenueDto from, Venue to);
//        /// <summary>
//        /// mapper to Venue
//        /// </summary>
//        /// <returns></returns>
//        public static Venue MapperToVenue(this VenueDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new Venue()
//            {
//                Name = model.Name,
//                Address = model.Address,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate TImplClass-TDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class TDto
//    {
//        /// <inheritdoc cref = "TImplClass.World"/>
//        [Required]
//        [Description("hello world")]
//        public string? World { get; set; }

//        /// <inheritdoc cref = "TImplClass.Email"/>
//        [EmailAddress]
//        public string? Email { get; set; }

//        /// <inheritdoc cref = "TImplClass.HostUrl"/>
//        [Url]
//        public string HostUrl { get; set; }

//        /// <inheritdoc cref = "TImplClass.PhoneNumber"/>
//        [Phone]
//        public string PhoneNumber { get; set; }

//        /// <inheritdoc cref = "TImplClass.RegText"/>
//        [RegularExpression("^[a-zA-Z0-9]+$", ErrorMessage = "Only alphanumeric characters are allowed.")]
//        public string? RegText { get; set; }

//        /// <inheritdoc cref = "TClass.Hello"/>
//        [StringLength(100, MinimumLength = 5)]
//        public string? Hello { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class TImplClassToTDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(TImplClass from, TDto to);
//        /// <summary>
//        /// mapper to TDto
//        /// </summary>
//        /// <returns></returns>
//        public static TDto MapperToTDto(this TImplClass model)
//        {
//            if (model == null)
//                return null;
//            var retn = new TDto()
//            {
//                World = model.World,
//                Email = model.Email,
//                HostUrl = model.HostUrl,
//                PhoneNumber = model.PhoneNumber,
//                RegText = model.RegText,
//                Hello = model.Hello,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo TDto
//        /// </summary>
//        public static IQueryable<TDto> ProjectToTDto(this IQueryable<TImplClass> query)
//        {
//            return query.Select(model => model.MapperToTDto());
//        }
//    }

//    public static partial class TDtoToTImplClassExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(TDto from, TImplClass to);
//        /// <summary>
//        /// mapper to TImplClass
//        /// </summary>
//        /// <returns></returns>
//        public static TImplClass MapperToTImplClass(this TDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new TImplClass()
//            {
//                World = model.World,
//                Email = model.Email,
//                HostUrl = model.HostUrl,
//                PhoneNumber = model.PhoneNumber,
//                RegText = model.RegText,
//                Hello = model.Hello,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate Person-PersonComplexDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial record class PersonComplexDto
//    {
//        /// <inheritdoc cref = "Person.Name"/>
//        [Required]
//        public string Name { get; set; }

//        /// <inheritdoc cref = "Person.Age"/>
//        [Required]
//        [Range(0, 200)]
//        public int Age { get; set; }
//        /// <inheritdoc cref = "Person.Address"/>
//        public AddressDto Address { get; set; }
//        /// <inheritdoc cref = "Person.Hobbies"/>
//        public System.Collections.Generic.List<HobbyDto> Hobbies { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class PersonToPersonComplexDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(Person from, PersonComplexDto to);
//        /// <summary>
//        /// mapper to PersonComplexDto
//        /// </summary>
//        /// <returns></returns>
//        public static PersonComplexDto MapperToPersonComplexDto(this Person model)
//        {
//            if (model == null)
//                return null;
//            var retn = new PersonComplexDto()
//            {
//                Name = model.Name,
//                Age = model.Age,
//                Address = model.Address?.MapperToAddressDto(),
//                Hobbies = model.Hobbies != null ? model.Hobbies.Select(x => x?.MapperToHobbyDto()).ToList() : null,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo PersonComplexDto
//        /// </summary>
//        public static IQueryable<PersonComplexDto> ProjectToPersonComplexDto(this IQueryable<Person> query)
//        {
//            return query.Select(model => model.MapperToPersonComplexDto());
//        }
//    }

//    public static partial class PersonComplexDtoToPersonExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(PersonComplexDto from, Person to);
//        /// <summary>
//        /// mapper to Person
//        /// </summary>
//        /// <returns></returns>
//        public static Person MapperToPerson(this PersonComplexDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new Person()
//            {
//                Name = model.Name,
//                Age = model.Age,
//                Address = model.Address?.MapperToAddress(),
//                Hobbies = model.Hobbies != null ? model.Hobbies.Select(x => x?.MapperToHobby()).ToList() : null,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate Person-PersonDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial record class PersonDto
//    {
//        /// <inheritdoc cref = "Person.Name"/>
//        [Required]
//        public string Name { get; set; }

//        /// <inheritdoc cref = "Person.Age"/>
//        [Required]
//        [Range(0, 200)]
//        public int Age { get; set; }
//        /// <inheritdoc cref = "Person.Address"/>
//        public Biwen.AutoClassGen.TestConsole.Dtos.Address Address { get; set; }
//        /// <inheritdoc cref = "Person.Hobbies"/>
//        public System.Collections.Generic.List<Biwen.AutoClassGen.TestConsole.Dtos.Hobby> Hobbies { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class PersonToPersonDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(Person from, PersonDto to);
//        /// <summary>
//        /// mapper to PersonDto
//        /// </summary>
//        /// <returns></returns>
//        public static PersonDto MapperToPersonDto(this Person model)
//        {
//            if (model == null)
//                return null;
//            var retn = new PersonDto()
//            {
//                Name = model.Name,
//                Age = model.Age,
//                Address = model.Address,
//                Hobbies = model.Hobbies,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo PersonDto
//        /// </summary>
//        public static IQueryable<PersonDto> ProjectToPersonDto(this IQueryable<Person> query)
//        {
//            return query.Select(model => model.MapperToPersonDto());
//        }
//    }

//    public static partial class PersonDtoToPersonExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(PersonDto from, Person to);
//        /// <summary>
//        /// mapper to Person
//        /// </summary>
//        /// <returns></returns>
//        public static Person MapperToPerson(this PersonDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new Person()
//            {
//                Name = model.Name,
//                Age = model.Age,
//                Address = model.Address,
//                Hobbies = model.Hobbies,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate Address-AddressDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class AddressDto
//    {
//        /// <inheritdoc cref = "Address.Street"/>
//        [Required]
//        public string Street { get; set; }

//        /// <inheritdoc cref = "Address.City"/>
//        [Required]
//        public string City { get; set; }

//        /// <inheritdoc cref = "Address.State"/>
//        [Required]
//        public string State { get; set; }

//        /// <inheritdoc cref = "Address.ZipCode"/>
//        [Required]
//        public string ZipCode { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;
//    using System.Net;

//    public static partial class AddressToAddressDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(Address from, AddressDto to);
//        /// <summary>
//        /// mapper to AddressDto
//        /// </summary>
//        /// <returns></returns>
//        public static AddressDto MapperToAddressDto(this Address model)
//        {
//            if (model == null)
//                return null;
//            var retn = new AddressDto()
//            {
//                Street = model.Street,
//                City = model.City,
//                State = model.State,
//                ZipCode = model.ZipCode,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo AddressDto
//        /// </summary>
//        public static IQueryable<AddressDto> ProjectToAddressDto(this IQueryable<Address> query)
//        {
//            return query.Select(model => model.MapperToAddressDto());
//        }
//    }

//    public static partial class AddressDtoToAddressExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(AddressDto from, Address to);
//        /// <summary>
//        /// mapper to Address
//        /// </summary>
//        /// <returns></returns>
//        public static Address MapperToAddress(this AddressDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new Address()
//            {
//                Street = model.Street,
//                City = model.City,
//                State = model.State,
//                ZipCode = model.ZipCode,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate Hobby-HobbyDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class HobbyDto
//    {
//        /// <inheritdoc cref = "Hobby.Name"/>
//        [Required]
//        public string Name { get; set; }

//        /// <inheritdoc cref = "Hobby.Description"/>
//        [Required]
//        public string Description { get; set; }
//        /// <inheritdoc cref = "Hobby.Extend"/>
//        public HobbyExtendDto Extend { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class HobbyToHobbyDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(Hobby from, HobbyDto to);
//        /// <summary>
//        /// mapper to HobbyDto
//        /// </summary>
//        /// <returns></returns>
//        public static HobbyDto MapperToHobbyDto(this Hobby model)
//        {
//            if (model == null)
//                return null;
//            var retn = new HobbyDto()
//            {
//                Name = model.Name,
//                Description = model.Description,
//                Extend = model.Extend?.MapperToHobbyExtendDto(),
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo HobbyDto
//        /// </summary>
//        public static IQueryable<HobbyDto> ProjectToHobbyDto(this IQueryable<Hobby> query)
//        {
//            return query.Select(model => model.MapperToHobbyDto());
//        }
//    }

//    public static partial class HobbyDtoToHobbyExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(HobbyDto from, Hobby to);
//        /// <summary>
//        /// mapper to Hobby
//        /// </summary>
//        /// <returns></returns>
//        public static Hobby MapperToHobby(this HobbyDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new Hobby()
//            {
//                Name = model.Name,
//                Description = model.Description,
//                Extend = model.Extend?.MapperToHobbyExtend(),
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate HobbyExtend-HobbyExtendDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class HobbyExtendDto
//    {
//        /// <inheritdoc cref = "HobbyExtend.Extend1"/>
//        public string Extend1 { get; set; }
//        /// <inheritdoc cref = "HobbyExtend.Extend2"/>
//        public string Extend2 { get; set; }
//        /// <inheritdoc cref = "HobbyExtend.Extend3"/>
//        public InnerExtendDto Extend3 { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class HobbyExtendToHobbyExtendDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(HobbyExtend from, HobbyExtendDto to);
//        /// <summary>
//        /// mapper to HobbyExtendDto
//        /// </summary>
//        /// <returns></returns>
//        public static HobbyExtendDto MapperToHobbyExtendDto(this HobbyExtend model)
//        {
//            if (model == null)
//                return null;
//            var retn = new HobbyExtendDto()
//            {
//                Extend1 = model.Extend1,
//                Extend2 = model.Extend2,
//                Extend3 = model.Extend3?.MapperToInnerExtendDto(),
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo HobbyExtendDto
//        /// </summary>
//        public static IQueryable<HobbyExtendDto> ProjectToHobbyExtendDto(this IQueryable<HobbyExtend> query)
//        {
//            return query.Select(model => model.MapperToHobbyExtendDto());
//        }
//    }

//    public static partial class HobbyExtendDtoToHobbyExtendExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(HobbyExtendDto from, HobbyExtend to);
//        /// <summary>
//        /// mapper to HobbyExtend
//        /// </summary>
//        /// <returns></returns>
//        public static HobbyExtend MapperToHobbyExtend(this HobbyExtendDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new HobbyExtend()
//            {
//                Extend1 = model.Extend1,
//                Extend2 = model.Extend2,
//                Extend3 = model.Extend3?.MapperToInnerExtend(),
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}

////generate InnerExtend-InnerExtendDto
//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;

//    public partial class InnerExtendDto
//    {
//        /// <inheritdoc cref = "InnerExtend.InnerExtendMsg"/>
//        public string InnerExtendMsg { get; set; }
//    }
//}

//namespace Biwen.AutoClassGen.TestConsole.Dtos
//{
//    using Biwen.AutoClassGen.TestConsole.Dtos;
//    using System.Linq;

//    public static partial class InnerExtendToInnerExtendDtoExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(InnerExtend from, InnerExtendDto to);
//        /// <summary>
//        /// mapper to InnerExtendDto
//        /// </summary>
//        /// <returns></returns>
//        public static InnerExtendDto MapperToInnerExtendDto(this InnerExtend model)
//        {
//            if (model == null)
//                return null;
//            var retn = new InnerExtendDto()
//            {
//                InnerExtendMsg = model.InnerExtendMsg,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }

//        /// <summary>
//        /// ProjectTo InnerExtendDto
//        /// </summary>
//        public static IQueryable<InnerExtendDto> ProjectToInnerExtendDto(this IQueryable<InnerExtend> query)
//        {
//            return query.Select(model => model.MapperToInnerExtendDto());
//        }
//    }

//    public static partial class InnerExtendDtoToInnerExtendExtentions
//    {
//        /// <summary>
//        /// custom mapper
//        /// </summary>
//        static partial void MapperToPartial(InnerExtendDto from, InnerExtend to);
//        /// <summary>
//        /// mapper to InnerExtend
//        /// </summary>
//        /// <returns></returns>
//        public static InnerExtend MapperToInnerExtend(this InnerExtendDto model)
//        {
//            if (model == null)
//                return null;
//            var retn = new InnerExtend()
//            {
//                InnerExtendMsg = model.InnerExtendMsg,
//            };
//            MapperToPartial(model, retn);
//            return retn;
//        }
//    }
//}
//#pragma warning restore
