//// <auto-generated />
//// author:vipwan@outlook.com 万雅虎
//// issue:https://github.com/vipwan/Biwen.AutoClassGen/issues
//// 如果你在使用中遇到问题,请第一时间issue,谢谢!
//// This file is generated by Biwen.AutoClassGen.AutoInjectSourceGenerator
//#pragma warning disable

//public static partial class ServiceCollectionExtension
//{

//    /// <summary>
//    /// 自动注册标注的服务
//    /// </summary>
//    /// <param name = "services"></param>
//    /// <returns></returns>
//    public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoInjectX(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
//    {
//        services.AddScoped<Biwen.AutoClassGen.TestConsole.Services.TestService>();
//        return services;
//    }
//}

//#pragma warning restore
